---
title: "lab-07-simpsons.Rmd"
author: Fawzaih Nazal
date: 17 March 2021
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages

```{r load_libraries, message=FALSE}
library(tidyverse) 
library(mosaicData)
```


## Exercises


1.  
```{r whickam}
Whickham
```
    
Your answer: The data is observational as the description states that is based on age, smoking, and mortality, which are all observable events and not produced via experiments

2.  
```{r observations}
nrow( Whickham)
```

Your answer;There 1,314 observations.As we know every row is an observation

3.  

```{r number_variables}

```

Your answer:  

```{r var_type}

```

Your answer: 

```{r plot_outcome}

```


```{r plot_smoker}

```

```{r plot_age}

```


4. 

```{r plot_smokeVSincome_1}

```

Knit, commit, and push to github.

5. 

```{r plot_smokeVSincome_2}
Whickham %>%
  count(smoker, outcome)
```

6.

```{r age_cat}

```

7. 

```{r plot_smokeVSincome_3}

```

Knit, commit, and push to github.